functionsDirectory = "C:\\Users\\info\\.gemini\\antgravity\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
headers = []
redirects = []

[functions]

[functions."*"]

[[plugins]]
origin = "config"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[build]
publish = "C:\\Users\\info\\.gemini\\antgravity\\.next"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "C:\\Users\\info\\.gemini\\antgravity\\netlify\\functions"

[build.environment]
NEXT_PUBLIC_SUPABASE_URL = "https://jssoyjwjqykcuovdydtz.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_RztM_8dNswdYyCo_3ZTFyA_94mkh6xz"
NEXT_PUBLIC_LIFF_ID = "2009817872-zldmH8LW"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]