-- 総会会計: 標準科目 / 科目 / 予算 / 決算明細
-- Supabase SQL Editorで全文を実行してください。

CREATE TABLE IF NOT EXISTS public.assembly_standard_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL CHECK (type IN ('income', 'expense')),
  name TEXT NOT NULL,
  sort_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (type, name)
);

INSERT INTO public.assembly_standard_categories (type, name, sort_order, is_active)
VALUES
  ('income', '会費', 10, TRUE),
  ('income', '補助金', 20, TRUE),
  ('income', '事業収入', 30, TRUE),
  ('income', '繰越金', 40, TRUE),
  ('income', '雑入', 50, TRUE),
  ('expense', '会議費', 110, TRUE),
  ('expense', '事務費', 120, TRUE),
  ('expense', '印刷費', 130, TRUE),
  ('expense', '通信費', 140, TRUE),
  ('expense', '集会所管理費', 150, TRUE),
  ('expense', '慶弔費', 160, TRUE),
  ('expense', '事業費', 170, TRUE),
  ('expense', '支払手数料', 180, TRUE),
  ('expense', '予備費', 190, TRUE)
ON CONFLICT (type, name) DO UPDATE
SET sort_order = EXCLUDED.sort_order,
    is_active = TRUE,
    updated_at = NOW();

CREATE TABLE IF NOT EXISTS public.assembly_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  neighborhood_id BIGINT NOT NULL REFERENCES public.neighborhoods(id) ON DELETE CASCADE,
  fiscal_year INTEGER,
  type TEXT NOT NULL CHECK (type IN ('income', 'expense')),
  name TEXT NOT NULL,
  parent_id BIGINT REFERENCES public.assembly_categories(id) ON DELETE CASCADE,
  sort_order INTEGER DEFAULT 0,
  is_standard BOOLEAN DEFAULT FALSE,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.assembly_categories
  ADD COLUMN IF NOT EXISTS neighborhood_id BIGINT REFERENCES public.neighborhoods(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS fiscal_year INTEGER,
  ADD COLUMN IF NOT EXISTS type TEXT,
  ADD COLUMN IF NOT EXISTS name TEXT,
  ADD COLUMN IF NOT EXISTS parent_id BIGINT REFERENCES public.assembly_categories(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS is_standard BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

CREATE TABLE IF NOT EXISTS public.assembly_budgets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  neighborhood_id BIGINT NOT NULL REFERENCES public.neighborhoods(id) ON DELETE CASCADE,
  fiscal_year INTEGER NOT NULL,
  category_id BIGINT NOT NULL REFERENCES public.assembly_categories(id) ON DELETE CASCADE,
  budget_amount NUMERIC DEFAULT 0,
  previous_budget_amount NUMERIC DEFAULT 0,
  note TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.assembly_budgets
  ADD COLUMN IF NOT EXISTS neighborhood_id BIGINT REFERENCES public.neighborhoods(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS fiscal_year INTEGER,
  ADD COLUMN IF NOT EXISTS category_id BIGINT REFERENCES public.assembly_categories(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS budget_amount NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS previous_budget_amount NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS note TEXT,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

CREATE UNIQUE INDEX IF NOT EXISTS assembly_budgets_neighborhood_year_category_unique
  ON public.assembly_budgets (neighborhood_id, fiscal_year, category_id);

CREATE TABLE IF NOT EXISTS public.assembly_settlements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  neighborhood_id BIGINT NOT NULL REFERENCES public.neighborhoods(id) ON DELETE CASCADE,
  fiscal_year INTEGER NOT NULL,
  category_id BIGINT REFERENCES public.assembly_categories(id) ON DELETE SET NULL,
  type TEXT NOT NULL CHECK (type IN ('income', 'expense')),
  amount NUMERIC DEFAULT 0,
  paid_date DATE,
  description TEXT,
  receipt_url TEXT,
  receipt_name TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.assembly_settlements
  ADD COLUMN IF NOT EXISTS neighborhood_id BIGINT REFERENCES public.neighborhoods(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS fiscal_year INTEGER,
  ADD COLUMN IF NOT EXISTS category_id BIGINT REFERENCES public.assembly_categories(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS type TEXT,
  ADD COLUMN IF NOT EXISTS amount NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS paid_date DATE,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS receipt_url TEXT,
  ADD COLUMN IF NOT EXISTS receipt_name TEXT,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE public.assembly_settlements
  ALTER COLUMN category_id DROP NOT NULL;

DO $$
DECLARE
  target_constraint TEXT;
BEGIN
  FOR target_constraint IN
    SELECT c.conname
    FROM pg_constraint c
    JOIN pg_class t ON t.oid = c.conrelid
    JOIN pg_namespace n ON n.oid = t.relnamespace
    WHERE n.nspname = 'public'
      AND t.relname = 'assembly_settlements'
      AND c.contype = 'f'
      AND pg_get_constraintdef(c.oid) ILIKE '%assembly_categories%'
  LOOP
    EXECUTE format('ALTER TABLE public.assembly_settlements DROP CONSTRAINT %I', target_constraint);
  END LOOP;
END $$;

ALTER TABLE public.assembly_settlements
  ADD CONSTRAINT assembly_settlements_category_id_fkey
  FOREIGN KEY (category_id)
  REFERENCES public.assembly_categories(id)
  ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS assembly_categories_neighborhood_idx
  ON public.assembly_categories (neighborhood_id, type, sort_order);

CREATE INDEX IF NOT EXISTS assembly_settlements_neighborhood_year_idx
  ON public.assembly_settlements (neighborhood_id, fiscal_year, paid_date);

INSERT INTO storage.buckets (id, name, public)
VALUES ('attachments', 'attachments', TRUE)
ON CONFLICT (id) DO NOTHING;

DO $$
BEGIN
  CREATE POLICY "attachments public select"
    ON storage.objects FOR SELECT
    USING (bucket_id = 'attachments');
EXCEPTION WHEN duplicate_object THEN
  NULL;
END $$;

DO $$
BEGIN
  CREATE POLICY "attachments authenticated insert"
    ON storage.objects FOR INSERT
    TO authenticated
    WITH CHECK (bucket_id = 'attachments');
EXCEPTION WHEN duplicate_object THEN
  NULL;
END $$;

ALTER TABLE public.assembly_standard_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assembly_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assembly_budgets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assembly_settlements ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS assembly_standard_categories_select_authenticated
ON public.assembly_standard_categories;

CREATE POLICY assembly_standard_categories_select_authenticated
ON public.assembly_standard_categories
FOR SELECT
TO authenticated
USING (TRUE);

DROP POLICY IF EXISTS assembly_categories_select_active_admins
ON public.assembly_categories;

CREATE POLICY assembly_categories_select_active_admins
ON public.assembly_categories
FOR SELECT
TO authenticated
USING (
  neighborhood_id IN (
    SELECT admins.neighborhood_id
    FROM public.neighborhood_admins admins
    WHERE admins.admin_auth_id = auth.uid()
      AND admins.status = 'active'
  )
);

DROP POLICY IF EXISTS assembly_categories_insert_active_admins
ON public.assembly_categories;

CREATE POLICY assembly_categories_insert_active_admins
ON public.assembly_categories
FOR INSERT
TO authenticated
WITH CHECK (
  neighborhood_id IN (
    SELECT admins.neighborhood_id
    FROM public.neighborhood_admins admins
    WHERE admins.admin_auth_id = auth.uid()
      AND admins.status = 'active'
  )
);

DROP POLICY IF EXISTS assembly_categories_update_active_admins
ON public.assembly_categories;

CREATE POLICY assembly_categories_update_active_admins
ON public.assembly_categories
FOR UPDATE
TO authenticated
USING (
  neighborhood_id IN (
    SELECT admins.neighborhood_id
    FROM public.neighborhood_admins admins
    WHERE admins.admin_auth_id = auth.uid()
      AND admins.status = 'active'
  )
)
WITH CHECK (
  neighborhood_id IN (
    SELECT admins.neighborhood_id
    FROM public.neighborhood_admins admins
    WHERE admins.admin_auth_id = auth.uid()
      AND admins.status = 'active'
  )
);

DROP POLICY IF EXISTS assembly_categories_delete_active_admins
ON public.assembly_categories;

CREATE POLICY assembly_categories_delete_active_admins
ON public.assembly_categories
FOR DELETE
TO authenticated
USING (
  neighborhood_id IN (
    SELECT admins.neighborhood_id
    FROM public.neighborhood_admins admins
    WHERE admins.admin_auth_id = auth.uid()
      AND admins.status = 'active'
  )
);

DROP POLICY IF EXISTS assembly_budgets_select_active_admins
ON public.assembly_budgets;

CREATE POLICY assembly_budgets_select_active_admins
ON public.assembly_budgets
FOR SELECT
TO authenticated
USING (
  neighborhood_id IN (
    SELECT admins.neighborhood_id
    FROM public.neighborhood_admins admins
    WHERE admins.admin_auth_id = auth.uid()
      AND admins.status = 'active'
  )
);

DROP POLICY IF EXISTS assembly_budgets_insert_active_admins
ON public.assembly_budgets;

CREATE POLICY assembly_budgets_insert_active_admins
ON public.assembly_budgets
FOR INSERT
TO authenticated
WITH CHECK (
  neighborhood_id IN (
    SELECT admins.neighborhood_id
    FROM public.neighborhood_admins admins
    WHERE admins.admin_auth_id = auth.uid()
      AND admins.status = 'active'
  )
);

DROP POLICY IF EXISTS assembly_budgets_update_active_admins
ON public.assembly_budgets;

CREATE POLICY assembly_budgets_update_active_admins
ON public.assembly_budgets
FOR UPDATE
TO authenticated
USING (
  neighborhood_id IN (
    SELECT admins.neighborhood_id
    FROM public.neighborhood_admins admins
    WHERE admins.admin_auth_id = auth.uid()
      AND admins.status = 'active'
  )
)
WITH CHECK (
  neighborhood_id IN (
    SELECT admins.neighborhood_id
    FROM public.neighborhood_admins admins
    WHERE admins.admin_auth_id = auth.uid()
      AND admins.status = 'active'
  )
);

DROP POLICY IF EXISTS assembly_budgets_delete_active_admins
ON public.assembly_budgets;

CREATE POLICY assembly_budgets_delete_active_admins
ON public.assembly_budgets
FOR DELETE
TO authenticated
USING (
  neighborhood_id IN (
    SELECT admins.neighborhood_id
    FROM public.neighborhood_admins admins
    WHERE admins.admin_auth_id = auth.uid()
      AND admins.status = 'active'
  )
);

DROP POLICY IF EXISTS assembly_settlements_select_active_admins
ON public.assembly_settlements;

CREATE POLICY assembly_settlements_select_active_admins
ON public.assembly_settlements
FOR SELECT
TO authenticated
USING (
  neighborhood_id IN (
    SELECT admins.neighborhood_id
    FROM public.neighborhood_admins admins
    WHERE admins.admin_auth_id = auth.uid()
      AND admins.status = 'active'
  )
);

DROP POLICY IF EXISTS assembly_settlements_insert_active_admins
ON public.assembly_settlements;

CREATE POLICY assembly_settlements_insert_active_admins
ON public.assembly_settlements
FOR INSERT
TO authenticated
WITH CHECK (
  neighborhood_id IN (
    SELECT admins.neighborhood_id
    FROM public.neighborhood_admins admins
    WHERE admins.admin_auth_id = auth.uid()
      AND admins.status = 'active'
  )
);

DROP POLICY IF EXISTS assembly_settlements_update_active_admins
ON public.assembly_settlements;

CREATE POLICY assembly_settlements_update_active_admins
ON public.assembly_settlements
FOR UPDATE
TO authenticated
USING (
  neighborhood_id IN (
    SELECT admins.neighborhood_id
    FROM public.neighborhood_admins admins
    WHERE admins.admin_auth_id = auth.uid()
      AND admins.status = 'active'
  )
)
WITH CHECK (
  neighborhood_id IN (
    SELECT admins.neighborhood_id
    FROM public.neighborhood_admins admins
    WHERE admins.admin_auth_id = auth.uid()
      AND admins.status = 'active'
  )
);

DROP POLICY IF EXISTS assembly_settlements_delete_active_admins
ON public.assembly_settlements;

CREATE POLICY assembly_settlements_delete_active_admins
ON public.assembly_settlements
FOR DELETE
TO authenticated
USING (
  neighborhood_id IN (
    SELECT admins.neighborhood_id
    FROM public.neighborhood_admins admins
    WHERE admins.admin_auth_id = auth.uid()
      AND admins.status = 'active'
  )
);

NOTIFY pgrst, 'reload schema';

SELECT
  to_regclass('public.assembly_standard_categories') AS assembly_standard_categories,
  to_regclass('public.assembly_categories') AS assembly_categories,
  to_regclass('public.assembly_budgets') AS assembly_budgets,
  to_regclass('public.assembly_settlements') AS assembly_settlements;

COMMENT ON TABLE public.assembly_standard_categories IS '総会会計で初期作成する標準科目。各自治会の科目へコピーして編集する。';
COMMENT ON TABLE public.assembly_categories IS '自治会ごとの総会会計科目。parent_idで補助科目を表す。';
COMMENT ON TABLE public.assembly_budgets IS '会計年度ごとの科目別予算額。';
COMMENT ON TABLE public.assembly_settlements IS '会計年度ごとの決算明細。領収書画像/PDFのURLをreceipt_urlに保存する。';
