-- Live・施設予約機能
-- Supabase SQL Editorで実行してください。

CREATE TABLE IF NOT EXISTS public.live_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  neighborhood_id BIGINT REFERENCES public.neighborhoods(id) ON DELETE CASCADE,
  provider TEXT DEFAULT 'line',
  title TEXT NOT NULL,
  content TEXT,
  description TEXT,
  event_date DATE,
  event_time TEXT,
  starts_at TIMESTAMP WITH TIME ZONE,
  meeting_url TEXT,
  live_url TEXT,
  event_url TEXT,
  status TEXT DEFAULT 'scheduled',
  is_pushed BOOLEAN DEFAULT false,
  published_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.live_sessions
  ADD COLUMN IF NOT EXISTS neighborhood_id BIGINT REFERENCES public.neighborhoods(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS provider TEXT DEFAULT 'line',
  ADD COLUMN IF NOT EXISTS title TEXT,
  ADD COLUMN IF NOT EXISTS content TEXT,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS event_date DATE,
  ADD COLUMN IF NOT EXISTS event_time TEXT,
  ADD COLUMN IF NOT EXISTS starts_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS meeting_url TEXT,
  ADD COLUMN IF NOT EXISTS live_url TEXT,
  ADD COLUMN IF NOT EXISTS event_url TEXT,
  ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'scheduled',
  ADD COLUMN IF NOT EXISTS is_pushed BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS published_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

CREATE TABLE IF NOT EXISTS public.live_session_applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  live_session_id BIGINT REFERENCES public.live_sessions(id) ON DELETE CASCADE,
  session_id BIGINT,
  neighborhood_id BIGINT REFERENCES public.neighborhoods(id) ON DELETE CASCADE,
  roster_id BIGINT, -- Legacy compatibility only. resident_rosters.id is UUID.
  resident_roster_id UUID REFERENCES public.resident_rosters(id) ON DELETE SET NULL,
  user_auth_id TEXT,
  resident_name TEXT,
  applicant_name TEXT,
  participant_count INTEGER DEFAULT 1,
  people_count INTEGER DEFAULT 1,
  reply_status TEXT DEFAULT 'attend',
  response_status TEXT DEFAULT 'attend',
  status TEXT DEFAULT 'attend',
  applied_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.live_session_applications
  ADD COLUMN IF NOT EXISTS live_session_id BIGINT REFERENCES public.live_sessions(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS session_id BIGINT,
  ADD COLUMN IF NOT EXISTS neighborhood_id BIGINT REFERENCES public.neighborhoods(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS roster_id BIGINT,
  ADD COLUMN IF NOT EXISTS resident_roster_id UUID REFERENCES public.resident_rosters(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS user_auth_id TEXT,
  ADD COLUMN IF NOT EXISTS resident_name TEXT,
  ADD COLUMN IF NOT EXISTS applicant_name TEXT,
  ADD COLUMN IF NOT EXISTS participant_count INTEGER DEFAULT 1,
  ADD COLUMN IF NOT EXISTS people_count INTEGER DEFAULT 1,
  ADD COLUMN IF NOT EXISTS reply_status TEXT DEFAULT 'attend',
  ADD COLUMN IF NOT EXISTS response_status TEXT DEFAULT 'attend',
  ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'attend',
  ADD COLUMN IF NOT EXISTS applied_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

CREATE TABLE IF NOT EXISTS public.facilities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  neighborhood_id BIGINT REFERENCES public.neighborhoods(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  location TEXT,
  capacity TEXT,
  scale TEXT,
  available_hours TEXT,
  available_start_time TIME,
  available_end_time TIME,
  unavailable_weekdays TEXT[] DEFAULT '{}'::text[],
  unavailable_dates TEXT[] DEFAULT '{}'::text[],
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.facilities
  ADD COLUMN IF NOT EXISTS neighborhood_id BIGINT REFERENCES public.neighborhoods(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS name TEXT,
  ADD COLUMN IF NOT EXISTS location TEXT,
  ADD COLUMN IF NOT EXISTS capacity TEXT,
  ADD COLUMN IF NOT EXISTS scale TEXT,
  ADD COLUMN IF NOT EXISTS available_hours TEXT,
  ADD COLUMN IF NOT EXISTS available_start_time TIME,
  ADD COLUMN IF NOT EXISTS available_end_time TIME,
  ADD COLUMN IF NOT EXISTS unavailable_weekdays TEXT[] DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS unavailable_dates TEXT[] DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

CREATE TABLE IF NOT EXISTS public.facility_reservations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  facility_id BIGINT REFERENCES public.facilities(id) ON DELETE CASCADE,
  neighborhood_id BIGINT REFERENCES public.neighborhoods(id) ON DELETE CASCADE,
  roster_id BIGINT,
  user_auth_id TEXT,
  facility_name TEXT,
  applicant_name TEXT,
  resident_name TEXT,
  participant_count INTEGER DEFAULT 1,
  people_count INTEGER DEFAULT 1,
  reservation_date DATE,
  start_time TEXT,
  end_time TEXT,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.facility_reservations
  ADD COLUMN IF NOT EXISTS facility_id BIGINT REFERENCES public.facilities(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS neighborhood_id BIGINT REFERENCES public.neighborhoods(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS roster_id BIGINT,
  ADD COLUMN IF NOT EXISTS user_auth_id TEXT,
  ADD COLUMN IF NOT EXISTS facility_name TEXT,
  ADD COLUMN IF NOT EXISTS applicant_name TEXT,
  ADD COLUMN IF NOT EXISTS resident_name TEXT,
  ADD COLUMN IF NOT EXISTS participant_count INTEGER DEFAULT 1,
  ADD COLUMN IF NOT EXISTS people_count INTEGER DEFAULT 1,
  ADD COLUMN IF NOT EXISTS reservation_date DATE,
  ADD COLUMN IF NOT EXISTS start_time TEXT,
  ADD COLUMN IF NOT EXISTS end_time TEXT,
  ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

CREATE INDEX IF NOT EXISTS idx_live_sessions_neighborhood_date
  ON public.live_sessions(neighborhood_id, event_date);

CREATE INDEX IF NOT EXISTS idx_live_session_applications_session
  ON public.live_session_applications(live_session_id, applied_at);

CREATE UNIQUE INDEX IF NOT EXISTS idx_live_session_applications_unique_resident
  ON public.live_session_applications(live_session_id, resident_roster_id)
  WHERE live_session_id IS NOT NULL AND resident_roster_id IS NOT NULL;

ALTER TABLE public.live_session_applications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS live_session_applications_select_active_admins
ON public.live_session_applications;

CREATE POLICY live_session_applications_select_active_admins
ON public.live_session_applications
FOR SELECT
TO authenticated
USING (
  neighborhood_id IN (
    SELECT admins.neighborhood_id
    FROM public.neighborhood_admins admins
    WHERE admins.admin_auth_id = auth.uid()
      AND admins.status = 'active'
  )
);

CREATE INDEX IF NOT EXISTS idx_facilities_neighborhood
  ON public.facilities(neighborhood_id, is_active);

CREATE INDEX IF NOT EXISTS idx_facility_reservations_facility_date_status
  ON public.facility_reservations(facility_id, reservation_date, status);

ALTER TABLE public.live_sessions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS live_sessions_select_town_members
ON public.live_sessions;

CREATE POLICY live_sessions_select_town_members
ON public.live_sessions
FOR SELECT
TO authenticated
USING (
  neighborhood_id IN (
    SELECT admins.neighborhood_id
    FROM public.neighborhood_admins admins
    WHERE admins.admin_auth_id = auth.uid()
      AND admins.status = 'active'
  )
  OR neighborhood_id IN (
    SELECT rosters.neighborhood_id
    FROM public.resident_rosters rosters
    WHERE (
        rosters.user_auth_id::text = auth.uid()::text
        OR rosters.family_user_auth_id_1::text = auth.uid()::text
        OR rosters.family_user_auth_id_2::text = auth.uid()::text
      )
      AND COALESCE(rosters.withdrawal_status, 'active') <> 'withdrawn'
  )
);

DROP POLICY IF EXISTS live_sessions_insert_active_admins
ON public.live_sessions;

CREATE POLICY live_sessions_insert_active_admins
ON public.live_sessions
FOR INSERT
TO authenticated
WITH CHECK (
  neighborhood_id IN (
    SELECT admins.neighborhood_id
    FROM public.neighborhood_admins admins
    WHERE admins.admin_auth_id = auth.uid()
      AND admins.status = 'active'
  )
);

DROP POLICY IF EXISTS live_sessions_update_active_admins
ON public.live_sessions;

CREATE POLICY live_sessions_update_active_admins
ON public.live_sessions
FOR UPDATE
TO authenticated
USING (
  neighborhood_id IN (
    SELECT admins.neighborhood_id
    FROM public.neighborhood_admins admins
    WHERE admins.admin_auth_id = auth.uid()
      AND admins.status = 'active'
  )
)
WITH CHECK (
  neighborhood_id IN (
    SELECT admins.neighborhood_id
    FROM public.neighborhood_admins admins
    WHERE admins.admin_auth_id = auth.uid()
      AND admins.status = 'active'
  )
);

DROP POLICY IF EXISTS live_sessions_delete_active_admins
ON public.live_sessions;

CREATE POLICY live_sessions_delete_active_admins
ON public.live_sessions
FOR DELETE
TO authenticated
USING (
  neighborhood_id IN (
    SELECT admins.neighborhood_id
    FROM public.neighborhood_admins admins
    WHERE admins.admin_auth_id = auth.uid()
      AND admins.status = 'active'
  )
);

ALTER TABLE public.facilities ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS facilities_select_town_members
ON public.facilities;

CREATE POLICY facilities_select_town_members
ON public.facilities
FOR SELECT
TO authenticated
USING (
  neighborhood_id IN (
    SELECT admins.neighborhood_id
    FROM public.neighborhood_admins admins
    WHERE admins.admin_auth_id = auth.uid()
      AND admins.status = 'active'
  )
  OR neighborhood_id IN (
    SELECT rosters.neighborhood_id
    FROM public.resident_rosters rosters
    WHERE (
        rosters.user_auth_id::text = auth.uid()::text
        OR rosters.family_user_auth_id_1::text = auth.uid()::text
        OR rosters.family_user_auth_id_2::text = auth.uid()::text
      )
      AND COALESCE(rosters.withdrawal_status, 'active') <> 'withdrawn'
  )
);

DROP POLICY IF EXISTS facilities_insert_active_admins
ON public.facilities;

CREATE POLICY facilities_insert_active_admins
ON public.facilities
FOR INSERT
TO authenticated
WITH CHECK (
  neighborhood_id IN (
    SELECT admins.neighborhood_id
    FROM public.neighborhood_admins admins
    WHERE admins.admin_auth_id = auth.uid()
      AND admins.status = 'active'
  )
);

DROP POLICY IF EXISTS facilities_update_active_admins
ON public.facilities;

CREATE POLICY facilities_update_active_admins
ON public.facilities
FOR UPDATE
TO authenticated
USING (
  neighborhood_id IN (
    SELECT admins.neighborhood_id
    FROM public.neighborhood_admins admins
    WHERE admins.admin_auth_id = auth.uid()
      AND admins.status = 'active'
  )
)
WITH CHECK (
  neighborhood_id IN (
    SELECT admins.neighborhood_id
    FROM public.neighborhood_admins admins
    WHERE admins.admin_auth_id = auth.uid()
      AND admins.status = 'active'
  )
);

DROP POLICY IF EXISTS facilities_delete_active_admins
ON public.facilities;

CREATE POLICY facilities_delete_active_admins
ON public.facilities
FOR DELETE
TO authenticated
USING (
  neighborhood_id IN (
    SELECT admins.neighborhood_id
    FROM public.neighborhood_admins admins
    WHERE admins.admin_auth_id = auth.uid()
      AND admins.status = 'active'
  )
);

ALTER TABLE public.facility_reservations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS facility_reservations_select_town_members
ON public.facility_reservations;

CREATE POLICY facility_reservations_select_town_members
ON public.facility_reservations
FOR SELECT
TO authenticated
USING (
  neighborhood_id IN (
    SELECT admins.neighborhood_id
    FROM public.neighborhood_admins admins
    WHERE admins.admin_auth_id = auth.uid()
      AND admins.status = 'active'
  )
  OR neighborhood_id IN (
    SELECT rosters.neighborhood_id
    FROM public.resident_rosters rosters
    WHERE (
        rosters.user_auth_id::text = auth.uid()::text
        OR rosters.family_user_auth_id_1::text = auth.uid()::text
        OR rosters.family_user_auth_id_2::text = auth.uid()::text
      )
      AND COALESCE(rosters.withdrawal_status, 'active') <> 'withdrawn'
  )
);

DROP POLICY IF EXISTS facility_reservations_insert_town_residents
ON public.facility_reservations;

CREATE POLICY facility_reservations_insert_town_residents
ON public.facility_reservations
FOR INSERT
TO authenticated
WITH CHECK (
  neighborhood_id IN (
    SELECT rosters.neighborhood_id
    FROM public.resident_rosters rosters
    WHERE (
        rosters.user_auth_id::text = auth.uid()::text
        OR rosters.family_user_auth_id_1::text = auth.uid()::text
        OR rosters.family_user_auth_id_2::text = auth.uid()::text
      )
      AND COALESCE(rosters.withdrawal_status, 'active') <> 'withdrawn'
  )
);

DROP POLICY IF EXISTS facility_reservations_update_active_admins
ON public.facility_reservations;

CREATE POLICY facility_reservations_update_active_admins
ON public.facility_reservations
FOR UPDATE
TO authenticated
USING (
  neighborhood_id IN (
    SELECT admins.neighborhood_id
    FROM public.neighborhood_admins admins
    WHERE admins.admin_auth_id = auth.uid()
      AND admins.status = 'active'
  )
)
WITH CHECK (
  neighborhood_id IN (
    SELECT admins.neighborhood_id
    FROM public.neighborhood_admins admins
    WHERE admins.admin_auth_id = auth.uid()
      AND admins.status = 'active'
  )
);

DROP POLICY IF EXISTS facility_reservations_delete_active_admins
ON public.facility_reservations;

CREATE POLICY facility_reservations_delete_active_admins
ON public.facility_reservations
FOR DELETE
TO authenticated
USING (
  neighborhood_id IN (
    SELECT admins.neighborhood_id
    FROM public.neighborhood_admins admins
    WHERE admins.admin_auth_id = auth.uid()
      AND admins.status = 'active'
  )
);

SELECT to_regclass('public.live_sessions') AS live_sessions_table;
NOTIFY pgrst, 'reload schema';
