-- 町内会・自治会 会費標準設定
-- Supabase SQL Editorで本番DBへ適用する。
-- 既存のfee_records（請求・入金実績）は更新しない。

CREATE OR REPLACE FUNCTION public.is_el_town_system_admin()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, auth
AS $$
  SELECT COALESCE(lower(auth.jwt() ->> 'email') = lower('admin@el-town.jp'), false);
$$;

REVOKE ALL ON FUNCTION public.is_el_town_system_admin() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_el_town_system_admin() TO authenticated;

CREATE TABLE IF NOT EXISTS public.membership_fee_standard_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version_number INTEGER NOT NULL UNIQUE CHECK (version_number > 0),
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'retired')),
  fee_name TEXT NOT NULL DEFAULT '年会費',
  default_amount INTEGER NOT NULL DEFAULT 3000 CHECK (default_amount >= 0),
  fiscal_year_start_month INTEGER NOT NULL DEFAULT 4 CHECK (fiscal_year_start_month BETWEEN 1 AND 12),
  billing_frequency TEXT NOT NULL DEFAULT 'annual' CHECK (billing_frequency IN ('annual')),
  billing_target TEXT NOT NULL DEFAULT 'active_households' CHECK (billing_target IN ('active_households')),
  cash_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  stripe_card_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  revenue_category TEXT NOT NULL DEFAULT '会費',
  change_reason TEXT NOT NULL,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL DEFAULT auth.uid(),
  published_at TIMESTAMP WITH TIME ZONE,
  retired_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS membership_fee_standard_one_published_idx
  ON public.membership_fee_standard_versions ((status))
  WHERE status = 'published';

CREATE TABLE IF NOT EXISTS public.neighborhood_fee_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  neighborhood_id BIGINT NOT NULL UNIQUE REFERENCES public.neighborhoods(id) ON DELETE CASCADE,
  standard_version_id BIGINT REFERENCES public.membership_fee_standard_versions(id) ON DELETE SET NULL,
  fee_name TEXT NOT NULL DEFAULT '年会費',
  amount INTEGER NOT NULL DEFAULT 3000 CHECK (amount >= 0),
  fiscal_year_start_month INTEGER NOT NULL DEFAULT 4 CHECK (fiscal_year_start_month BETWEEN 1 AND 12),
  billing_frequency TEXT NOT NULL DEFAULT 'annual' CHECK (billing_frequency IN ('annual')),
  billing_target TEXT NOT NULL DEFAULT 'active_households' CHECK (billing_target IN ('active_households')),
  cash_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  stripe_card_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  revenue_category TEXT NOT NULL DEFAULT '会費',
  overridden_fields JSONB NOT NULL DEFAULT '{}'::JSONB,
  applied_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS neighborhood_fee_settings_standard_version_idx
  ON public.neighborhood_fee_settings(standard_version_id);

CREATE TABLE IF NOT EXISTS public.membership_fee_standard_applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  standard_version_id BIGINT NOT NULL REFERENCES public.membership_fee_standard_versions(id) ON DELETE RESTRICT,
  neighborhood_id BIGINT NOT NULL REFERENCES public.neighborhoods(id) ON DELETE CASCADE,
  before_settings JSONB,
  after_settings JSONB NOT NULL,
  application_type TEXT NOT NULL CHECK (application_type IN ('new_neighborhood', 'initial_backfill', 'manual')),
  applied_by UUID REFERENCES auth.users(id) ON DELETE SET NULL DEFAULT auth.uid(),
  applied_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS membership_fee_standard_applications_lookup_idx
  ON public.membership_fee_standard_applications(neighborhood_id, applied_at DESC);

CREATE OR REPLACE FUNCTION public.set_membership_fee_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS membership_fee_standard_versions_updated_at
ON public.membership_fee_standard_versions;
CREATE TRIGGER membership_fee_standard_versions_updated_at
BEFORE UPDATE ON public.membership_fee_standard_versions
FOR EACH ROW EXECUTE FUNCTION public.set_membership_fee_updated_at();

DROP TRIGGER IF EXISTS neighborhood_fee_settings_updated_at
ON public.neighborhood_fee_settings;
CREATE TRIGGER neighborhood_fee_settings_updated_at
BEFORE UPDATE ON public.neighborhood_fee_settings
FOR EACH ROW EXECUTE FUNCTION public.set_membership_fee_updated_at();

CREATE OR REPLACE FUNCTION public.publish_membership_fee_standard(p_version_id BIGINT)
RETURNS public.membership_fee_standard_versions
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  published_version public.membership_fee_standard_versions;
BEGIN
  IF NOT public.is_el_town_system_admin() THEN
    RAISE EXCEPTION 'Only the el-town system administrator can publish membership fee standards.';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.membership_fee_standard_versions
    WHERE id = p_version_id
      AND status = 'draft'
  ) THEN
    RAISE EXCEPTION 'The requested draft membership fee standard was not found.';
  END IF;

  UPDATE public.membership_fee_standard_versions
  SET status = 'retired',
      retired_at = NOW()
  WHERE status = 'published';

  UPDATE public.membership_fee_standard_versions
  SET status = 'published',
      published_at = NOW(),
      retired_at = NULL
  WHERE id = p_version_id
  RETURNING * INTO published_version;

  RETURN published_version;
END;
$$;

REVOKE ALL ON FUNCTION public.publish_membership_fee_standard(BIGINT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.publish_membership_fee_standard(BIGINT) TO authenticated;

CREATE OR REPLACE FUNCTION public.copy_published_membership_fee_standard()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  standard public.membership_fee_standard_versions;
  inserted_setting public.neighborhood_fee_settings;
BEGIN
  SELECT *
    INTO standard
  FROM public.membership_fee_standard_versions
  WHERE status = 'published'
  ORDER BY version_number DESC
  LIMIT 1;

  IF standard.id IS NULL THEN
    RETURN NEW;
  END IF;

  INSERT INTO public.neighborhood_fee_settings (
    neighborhood_id,
    standard_version_id,
    fee_name,
    amount,
    fiscal_year_start_month,
    billing_frequency,
    billing_target,
    cash_enabled,
    stripe_card_enabled,
    revenue_category,
    applied_at
  )
  VALUES (
    NEW.id,
    standard.id,
    standard.fee_name,
    standard.default_amount,
    standard.fiscal_year_start_month,
    standard.billing_frequency,
    standard.billing_target,
    standard.cash_enabled,
    standard.stripe_card_enabled,
    standard.revenue_category,
    NOW()
  )
  ON CONFLICT (neighborhood_id) DO NOTHING
  RETURNING * INTO inserted_setting;

  IF inserted_setting.id IS NOT NULL THEN
    INSERT INTO public.membership_fee_standard_applications (
      standard_version_id,
      neighborhood_id,
      before_settings,
      after_settings,
      application_type
    )
    VALUES (
      standard.id,
      NEW.id,
      NULL,
      to_jsonb(inserted_setting),
      'new_neighborhood'
    );
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS neighborhoods_copy_membership_fee_standard
ON public.neighborhoods;
CREATE TRIGGER neighborhoods_copy_membership_fee_standard
AFTER INSERT ON public.neighborhoods
FOR EACH ROW
EXECUTE FUNCTION public.copy_published_membership_fee_standard();

ALTER TABLE public.membership_fee_standard_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.neighborhood_fee_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.membership_fee_standard_applications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS membership_fee_standard_versions_select_authenticated
ON public.membership_fee_standard_versions;
CREATE POLICY membership_fee_standard_versions_select_authenticated
  ON public.membership_fee_standard_versions
  FOR SELECT
  TO authenticated
  USING (TRUE);

DROP POLICY IF EXISTS membership_fee_standard_versions_insert_system_admin
ON public.membership_fee_standard_versions;
CREATE POLICY membership_fee_standard_versions_insert_system_admin
  ON public.membership_fee_standard_versions
  FOR INSERT
  TO authenticated
  WITH CHECK (public.is_el_town_system_admin());

DROP POLICY IF EXISTS membership_fee_standard_versions_update_system_admin
ON public.membership_fee_standard_versions;
CREATE POLICY membership_fee_standard_versions_update_system_admin
  ON public.membership_fee_standard_versions
  FOR UPDATE
  TO authenticated
  USING (public.is_el_town_system_admin())
  WITH CHECK (public.is_el_town_system_admin());

DROP POLICY IF EXISTS membership_fee_standard_versions_delete_system_admin
ON public.membership_fee_standard_versions;
CREATE POLICY membership_fee_standard_versions_delete_system_admin
  ON public.membership_fee_standard_versions
  FOR DELETE
  TO authenticated
  USING (public.is_el_town_system_admin() AND status = 'draft');

DROP POLICY IF EXISTS neighborhood_fee_settings_select_members
ON public.neighborhood_fee_settings;
CREATE POLICY neighborhood_fee_settings_select_members
  ON public.neighborhood_fee_settings
  FOR SELECT
  TO authenticated
  USING (
    public.is_el_town_system_admin()
    OR neighborhood_id IN (
      SELECT admins.neighborhood_id
      FROM public.neighborhood_admins AS admins
      WHERE admins.admin_auth_id::TEXT = auth.uid()::TEXT
        AND admins.status = 'active'
    )
    OR neighborhood_id IN (
      SELECT rosters.neighborhood_id
      FROM public.resident_rosters AS rosters
      WHERE rosters.user_auth_id::TEXT = auth.uid()::TEXT
         OR rosters.family_user_auth_id_1::TEXT = auth.uid()::TEXT
         OR rosters.family_user_auth_id_2::TEXT = auth.uid()::TEXT
    )
  );

DROP POLICY IF EXISTS neighborhood_fee_settings_write_active_admins
ON public.neighborhood_fee_settings;
CREATE POLICY neighborhood_fee_settings_write_active_admins
  ON public.neighborhood_fee_settings
  FOR ALL
  TO authenticated
  USING (
    neighborhood_id IN (
      SELECT admins.neighborhood_id
      FROM public.neighborhood_admins AS admins
      WHERE admins.admin_auth_id::TEXT = auth.uid()::TEXT
        AND admins.status = 'active'
    )
  )
  WITH CHECK (
    neighborhood_id IN (
      SELECT admins.neighborhood_id
      FROM public.neighborhood_admins AS admins
      WHERE admins.admin_auth_id::TEXT = auth.uid()::TEXT
        AND admins.status = 'active'
    )
  );

DROP POLICY IF EXISTS membership_fee_standard_applications_select_admins
ON public.membership_fee_standard_applications;
CREATE POLICY membership_fee_standard_applications_select_admins
  ON public.membership_fee_standard_applications
  FOR SELECT
  TO authenticated
  USING (
    public.is_el_town_system_admin()
    OR neighborhood_id IN (
      SELECT admins.neighborhood_id
      FROM public.neighborhood_admins AS admins
      WHERE admins.admin_auth_id::TEXT = auth.uid()::TEXT
        AND admins.status = 'active'
    )
  );

DROP POLICY IF EXISTS membership_fee_standard_applications_insert_system_admin
ON public.membership_fee_standard_applications;
CREATE POLICY membership_fee_standard_applications_insert_system_admin
  ON public.membership_fee_standard_applications
  FOR INSERT
  TO authenticated
  WITH CHECK (public.is_el_town_system_admin());

INSERT INTO public.membership_fee_standard_versions (
  version_number,
  status,
  fee_name,
  default_amount,
  fiscal_year_start_month,
  billing_frequency,
  billing_target,
  cash_enabled,
  stripe_card_enabled,
  revenue_category,
  change_reason,
  published_at
)
VALUES (
  1,
  'published',
  '年会費',
  3000,
  4,
  'annual',
  'active_households',
  TRUE,
  TRUE,
  '会費',
  '町内会・自治会の初期会費標準設定',
  NOW()
)
ON CONFLICT (version_number) DO NOTHING;

WITH standard AS (
  SELECT *
  FROM public.membership_fee_standard_versions
  WHERE status = 'published'
  ORDER BY version_number DESC
  LIMIT 1
),
inserted AS (
  INSERT INTO public.neighborhood_fee_settings (
    neighborhood_id,
    standard_version_id,
    fee_name,
    amount,
    fiscal_year_start_month,
    billing_frequency,
    billing_target,
    cash_enabled,
    stripe_card_enabled,
    revenue_category,
    applied_at
  )
  SELECT
    neighborhoods.id,
    standard.id,
    standard.fee_name,
    standard.default_amount,
    standard.fiscal_year_start_month,
    standard.billing_frequency,
    standard.billing_target,
    standard.cash_enabled,
    standard.stripe_card_enabled,
    standard.revenue_category,
    NOW()
  FROM public.neighborhoods AS neighborhoods
  CROSS JOIN standard
  WHERE NOT EXISTS (
    SELECT 1
    FROM public.neighborhood_fee_settings AS existing
    WHERE existing.neighborhood_id = neighborhoods.id
  )
  RETURNING *
)
INSERT INTO public.membership_fee_standard_applications (
  standard_version_id,
  neighborhood_id,
  before_settings,
  after_settings,
  application_type
)
SELECT
  inserted.standard_version_id,
  inserted.neighborhood_id,
  NULL,
  to_jsonb(inserted),
  'initial_backfill'
FROM inserted;

COMMENT ON TABLE public.membership_fee_standard_versions IS 'el-town全体の会費標準設定。公開済み版は上書きせず、版を追加する。';
COMMENT ON TABLE public.neighborhood_fee_settings IS '町内会・自治会ごとの会費設定。標準版と団体独自上書きを保持する。';
COMMENT ON TABLE public.membership_fee_standard_applications IS '会費標準設定を団体へ適用した履歴。';

NOTIFY pgrst, 'reload schema';
