-- 全団体共通のシステム利用料。適用開始月ごとに追加し、旧履歴を保持する。
CREATE TABLE IF NOT EXISTS public.system_usage_rate_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  effective_month TEXT NOT NULL UNIQUE CHECK (effective_month ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
  monthly_household_price INTEGER NOT NULL CHECK (monthly_household_price BETWEEN 0 AND 100000000),
  free_push_limit INTEGER NOT NULL CHECK (free_push_limit BETWEEN 0 AND 100000000),
  push_unit_price INTEGER NOT NULL CHECK (push_unit_price BETWEEN 0 AND 100000000),
  tax_rate NUMERIC(5,2) NOT NULL CHECK (tax_rate BETWEEN 0 AND 100),
  change_reason TEXT NOT NULL CHECK (length(trim(change_reason)) BETWEEN 1 AND 500),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE public.system_usage_rate_versions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.system_usage_rate_versions FROM anon, authenticated;
GRANT SELECT ON public.system_usage_rate_versions TO authenticated;
GRANT SELECT, INSERT ON public.system_usage_rate_versions TO service_role;
REVOKE UPDATE, DELETE, TRUNCATE ON public.system_usage_rate_versions FROM service_role;
GRANT USAGE, SELECT ON SEQUENCE public.system_usage_rate_versions_id_seq TO service_role;
DROP POLICY IF EXISTS system_usage_rates_read ON public.system_usage_rate_versions;
CREATE POLICY system_usage_rates_read ON public.system_usage_rate_versions FOR SELECT TO authenticated USING (true);
ALTER TABLE public.system_usage_billings
  ADD COLUMN IF NOT EXISTS rate_version_id BIGINT REFERENCES public.system_usage_rate_versions(id),
  ADD COLUMN IF NOT EXISTS rate_effective_month TEXT;
-- 過去の適用開始月は推測しない。画面から初回単価と適用開始月を登録する。
-- 保存済みの請求・接続数・単価・入金実績は変更しない。
NOTIFY pgrst, 'reload schema';
