-- システム管理 > システム利用料設定・月次請求 用の追加SQL
-- Supabase SQL Editor で実行してください。

ALTER TABLE public.system_settings
  ADD COLUMN IF NOT EXISTS monthly_household_price INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tax_rate NUMERIC(5, 2) DEFAULT 10;

COMMENT ON COLUMN public.system_settings.monthly_household_price IS 'システム利用料の接続数1件あたり月額単価。本人・家族アカウントのLINE連携数を対象にする。';
COMMENT ON COLUMN public.system_settings.tax_rate IS 'システム利用料の消費税率。例: 10。';

CREATE TABLE IF NOT EXISTS public.system_usage_billings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  neighborhood_id BIGINT REFERENCES public.neighborhoods(id) ON DELETE CASCADE,
  billing_month TEXT NOT NULL,
  linked_account_count INTEGER DEFAULT 0,
  push_count INTEGER DEFAULT 0,
  free_push_limit INTEGER DEFAULT 0,
  push_overage_count INTEGER DEFAULT 0,
  monthly_household_price INTEGER DEFAULT 0,
  push_unit_price INTEGER DEFAULT 0,
  subtotal_amount INTEGER DEFAULT 0,
  tax_rate NUMERIC(5, 2) DEFAULT 10,
  tax_amount INTEGER DEFAULT 0,
  total_amount INTEGER DEFAULT 0,
  invoice_number TEXT,
  receipt_number TEXT,
  invoice_issued_at TIMESTAMP WITH TIME ZONE,
  due_date TIMESTAMP WITH TIME ZONE,
  status TEXT DEFAULT 'billed',
  billed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  paid_amount INTEGER DEFAULT 0,
  payment_method TEXT,
  paid_at TIMESTAMP WITH TIME ZONE,
  stripe_checkout_session_id TEXT,
  stripe_payment_intent_id TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(neighborhood_id, billing_month)
);

ALTER TABLE public.system_usage_billings
  ADD COLUMN IF NOT EXISTS invoice_number TEXT,
  ADD COLUMN IF NOT EXISTS receipt_number TEXT,
  ADD COLUMN IF NOT EXISTS invoice_issued_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS due_date TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS paid_amount INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS payment_method TEXT,
  ADD COLUMN IF NOT EXISTS stripe_checkout_session_id TEXT,
  ADD COLUMN IF NOT EXISTS stripe_payment_intent_id TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS system_usage_billings_stripe_checkout_session_idx
  ON public.system_usage_billings(stripe_checkout_session_id)
  WHERE stripe_checkout_session_id IS NOT NULL;

COMMENT ON TABLE public.system_usage_billings IS 'el-townシステム利用料の月次請求。接続数、プッシュ超過、消費税を月ごとに固定して保存する。';
COMMENT ON COLUMN public.system_usage_billings.billing_month IS '請求対象月。YYYY-MM形式。';
COMMENT ON COLUMN public.system_usage_billings.linked_account_count IS '請求対象となるLINE連携アカウント数。本人・家族を含む。';
COMMENT ON COLUMN public.system_usage_billings.push_overage_count IS '無料プッシュ枠を超過した件数。';
COMMENT ON COLUMN public.system_usage_billings.subtotal_amount IS '税抜請求額。';
COMMENT ON COLUMN public.system_usage_billings.tax_amount IS '消費税額。';
COMMENT ON COLUMN public.system_usage_billings.total_amount IS '税込請求額。';
COMMENT ON COLUMN public.system_usage_billings.invoice_number IS '請求書番号。';
COMMENT ON COLUMN public.system_usage_billings.receipt_number IS '領収書番号。Stripe入金後に発番する。';
COMMENT ON COLUMN public.system_usage_billings.invoice_issued_at IS '請求書発行日。原則として利用月の翌月1日。';
COMMENT ON COLUMN public.system_usage_billings.due_date IS '支払期日。原則として利用月の翌月1日。';
COMMENT ON COLUMN public.system_usage_billings.paid_amount IS 'Stripeで入金された金額。';
COMMENT ON COLUMN public.system_usage_billings.payment_method IS '入金方法。システム利用料はstripeを想定する。';
COMMENT ON COLUMN public.system_usage_billings.stripe_checkout_session_id IS 'Stripe Checkout Session ID。';
COMMENT ON COLUMN public.system_usage_billings.stripe_payment_intent_id IS 'Stripe PaymentIntent ID。';

ALTER TABLE public.system_usage_billings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON public.system_usage_billings FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON public.system_usage_billings FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON public.system_usage_billings FOR UPDATE USING (true);
CREATE POLICY "Enable delete for all users" ON public.system_usage_billings FOR DELETE USING (true);
