-- el-town システム利用料: 団体別決済方法、16日実績固定、Stripe月次請求書
-- Supabase SQL Editorで本番DBへ適用する。

CREATE TABLE IF NOT EXISTS public.system_usage_payment_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  neighborhood_id BIGINT NOT NULL UNIQUE REFERENCES public.neighborhoods(id) ON DELETE CASCADE,
  payment_method TEXT CHECK (payment_method IN ('card', 'bank_transfer')),
  stripe_customer_id TEXT UNIQUE,
  stripe_default_payment_method_id TEXT,
  card_setup_status TEXT DEFAULT 'not_started',
  card_brand TEXT,
  card_last4 TEXT,
  card_exp_month INTEGER,
  card_exp_year INTEGER,
  bank_transfer_status TEXT,
  billing_email TEXT,
  billing_contact_name TEXT,
  automatic_collection_consent_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.system_usage_payment_profiles
  ADD COLUMN IF NOT EXISTS payment_method TEXT,
  ADD COLUMN IF NOT EXISTS stripe_customer_id TEXT,
  ADD COLUMN IF NOT EXISTS stripe_default_payment_method_id TEXT,
  ADD COLUMN IF NOT EXISTS card_setup_status TEXT DEFAULT 'not_started',
  ADD COLUMN IF NOT EXISTS card_brand TEXT,
  ADD COLUMN IF NOT EXISTS card_last4 TEXT,
  ADD COLUMN IF NOT EXISTS card_exp_month INTEGER,
  ADD COLUMN IF NOT EXISTS card_exp_year INTEGER,
  ADD COLUMN IF NOT EXISTS bank_transfer_status TEXT,
  ADD COLUMN IF NOT EXISTS billing_email TEXT,
  ADD COLUMN IF NOT EXISTS billing_contact_name TEXT,
  ADD COLUMN IF NOT EXISTS automatic_collection_consent_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

CREATE UNIQUE INDEX IF NOT EXISTS system_usage_payment_profiles_neighborhood_idx
  ON public.system_usage_payment_profiles(neighborhood_id);
CREATE UNIQUE INDEX IF NOT EXISTS system_usage_payment_profiles_customer_idx
  ON public.system_usage_payment_profiles(stripe_customer_id)
  WHERE stripe_customer_id IS NOT NULL;

ALTER TABLE public.system_usage_billings
  ADD COLUMN IF NOT EXISTS snapshot_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS snapshot_source TEXT,
  ADD COLUMN IF NOT EXISTS stripe_customer_id TEXT,
  ADD COLUMN IF NOT EXISTS stripe_invoice_id TEXT,
  ADD COLUMN IF NOT EXISTS stripe_hosted_invoice_url TEXT,
  ADD COLUMN IF NOT EXISTS stripe_invoice_pdf_url TEXT,
  ADD COLUMN IF NOT EXISTS stripe_last_error TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS system_usage_billings_stripe_invoice_idx
  ON public.system_usage_billings(stripe_invoice_id)
  WHERE stripe_invoice_id IS NOT NULL;

COMMENT ON TABLE public.system_usage_payment_profiles IS '町内会・自治会がel-townへ支払うシステム利用料のStripe顧客・決済方法。Connect受取口座とは別管理。';
COMMENT ON COLUMN public.system_usage_payment_profiles.payment_method IS 'card=保存カードによる自動決済、bank_transfer=団体専用仮想口座への振込。';
COMMENT ON COLUMN public.system_usage_payment_profiles.stripe_customer_id IS 'el-townプラットフォームStripeアカウント上のCustomer ID。';
COMMENT ON COLUMN public.system_usage_payment_profiles.automatic_collection_consent_at IS '団体管理者がカード自動決済を選択した日時。';
COMMENT ON COLUMN public.system_usage_billings.snapshot_at IS '接続数を固定した日時。原則として利用月16日。';
COMMENT ON COLUMN public.system_usage_billings.snapshot_source IS 'monthly_16th=16日定期固定、invoice_fallback=請求時の補完固定。';
COMMENT ON COLUMN public.system_usage_billings.stripe_invoice_id IS 'Stripe Invoice ID。カード自動決済と銀行振込で共通利用。';

ALTER TABLE public.system_usage_payment_profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable read access for system usage payment profiles" ON public.system_usage_payment_profiles;
CREATE POLICY "Enable read access for system usage payment profiles"
  ON public.system_usage_payment_profiles FOR SELECT USING (true);

-- 登録・更新はSUPABASE_SECRET_KEYを使用するサーバーAPIだけが行う。
