-- ==========================================
-- el-town システム改善 後半フェーズ DB移行スクリプト
-- SupabaseのSQL Editorに貼り付けて「RUN」を実行してください
-- ==========================================

-- 1. 家族登録（最大2名）のためのカラム追加
ALTER TABLE public.resident_rosters 
ADD COLUMN IF NOT EXISTS family_user_auth_id_1 TEXT,
ADD COLUMN IF NOT EXISTS family_user_auth_id_2 TEXT;

-- 2. 会費管理用テーブルの作成
CREATE TABLE IF NOT EXISTS public.fee_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roster_id BIGINT REFERENCES public.resident_rosters(id) ON DELETE CASCADE,
    year INT NOT NULL,
    paid_amount INT DEFAULT 0,
    unpaid_amount INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(roster_id, year)
);

-- 3. システム設定（プッシュ通知料金・基本会費設定）テーブルの作成
CREATE TABLE IF NOT EXISTS public.system_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    neighborhood_id BIGINT REFERENCES public.neighborhoods(id) ON DELETE CASCADE,
    push_unit_price INT DEFAULT 5, -- 超過時の1通あたりの単価
    free_push_limit INT DEFAULT 200, -- 無料で送れるプッシュ通知の枠
    annual_fee_amount INT DEFAULT 3000, -- デフォルトの年会費
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(neighborhood_id)
);

-- 4. 新規テーブルへのアクセス権限（既存のアプリからのアクセスを許可）
-- ※本番運用に向けてはRLSを有効化しますが、既存機能と合わせるためまずはパブリックアクセスを許可します
ALTER TABLE public.fee_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON public.fee_records FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON public.fee_records FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON public.fee_records FOR UPDATE USING (true);
CREATE POLICY "Enable delete for all users" ON public.fee_records FOR DELETE USING (true);

CREATE POLICY "Enable read access for all users" ON public.system_settings FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON public.system_settings FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON public.system_settings FOR UPDATE USING (true);
CREATE POLICY "Enable delete for all users" ON public.system_settings FOR DELETE USING (true);

-- 5. （参考）セキュリティ強化に関する確認
-- RLSがOFFになっている主要テーブルが存在する場合は、以下のコマンドで有効化し、適切なポリシーを設定する必要があります。
-- ALTER TABLE public.resident_rosters ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.event_applications ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.circulars ENABLE ROW LEVEL SECURITY;
