-- 発信機能: 電子回覧板 / 連絡 / イベント / 総会通知
-- Supabase SQL Editorで実行してください。

ALTER TABLE public.circulars
  ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'circular',
  ADD COLUMN IF NOT EXISTS author TEXT,
  ADD COLUMN IF NOT EXISTS author_name TEXT,
  ADD COLUMN IF NOT EXISTS body TEXT,
  ADD COLUMN IF NOT EXISTS attachments JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS attachment_url TEXT,
  ADD COLUMN IF NOT EXISTS image_url TEXT,
  ADD COLUMN IF NOT EXISTS pdf_url TEXT,
  ADD COLUMN IF NOT EXISTS event_date TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS event_time TEXT,
  ADD COLUMN IF NOT EXISTS meeting_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS requires_reply BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_pushed BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS proxy_template_text TEXT,
  ADD COLUMN IF NOT EXISTS published_at TIMESTAMP WITH TIME ZONE;

DO $$
DECLARE
  target_constraint TEXT;
BEGIN
  SELECT c.conname
    INTO target_constraint
  FROM pg_constraint c
  JOIN pg_class t ON t.oid = c.conrelid
  JOIN pg_namespace n ON n.oid = t.relnamespace
  WHERE n.nspname = 'public'
    AND t.relname = 'circulars'
    AND c.contype = 'c'
    AND pg_get_constraintdef(c.oid) ILIKE '%category%'
  LIMIT 1;

  IF target_constraint IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.circulars DROP CONSTRAINT %I', target_constraint);
  END IF;
END $$;

ALTER TABLE public.circulars
  ADD CONSTRAINT circulars_category_check
  CHECK (category IN ('circular', 'notice', 'info', 'event', 'assembly'));

UPDATE public.circulars
SET category = 'circular'
WHERE category IS NULL;

CREATE TABLE IF NOT EXISTS public.event_applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  circular_id BIGINT REFERENCES public.circulars(id) ON DELETE CASCADE,
  event_id BIGINT,
  assembly_notice_id BIGINT,
  neighborhood_id BIGINT REFERENCES public.neighborhoods(id) ON DELETE CASCADE,
  roster_id BIGINT,
  user_auth_id TEXT,
  resident_name TEXT NOT NULL,
  reply_status TEXT,
  response_status TEXT,
  adult_count INTEGER DEFAULT 0,
  child_count INTEGER DEFAULT 0,
  adults INTEGER DEFAULT 0,
  children INTEGER DEFAULT 0,
  proxy_file_url TEXT,
  proxy_text TEXT,
  proxy_signed_date DATE,
  proxy_signer_name TEXT,
  proxy_agent_name TEXT,
  proxy_url TEXT,
  attachment_url TEXT,
  applied_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.event_applications
  ADD COLUMN IF NOT EXISTS circular_id BIGINT REFERENCES public.circulars(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS event_id BIGINT,
  ADD COLUMN IF NOT EXISTS assembly_notice_id BIGINT,
  ADD COLUMN IF NOT EXISTS neighborhood_id BIGINT REFERENCES public.neighborhoods(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS roster_id BIGINT,
  ADD COLUMN IF NOT EXISTS user_auth_id TEXT,
  ADD COLUMN IF NOT EXISTS resident_name TEXT,
  ADD COLUMN IF NOT EXISTS reply_status TEXT,
  ADD COLUMN IF NOT EXISTS response_status TEXT,
  ADD COLUMN IF NOT EXISTS adult_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS child_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS adults INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS children INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS proxy_file_url TEXT,
  ADD COLUMN IF NOT EXISTS proxy_text TEXT,
  ADD COLUMN IF NOT EXISTS proxy_signed_date DATE,
  ADD COLUMN IF NOT EXISTS proxy_signer_name TEXT,
  ADD COLUMN IF NOT EXISTS proxy_agent_name TEXT,
  ADD COLUMN IF NOT EXISTS proxy_url TEXT,
  ADD COLUMN IF NOT EXISTS attachment_url TEXT,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

INSERT INTO storage.buckets (id, name, public)
VALUES ('attachments', 'attachments', true)
ON CONFLICT (id) DO NOTHING;

DO $$
BEGIN
  CREATE POLICY "attachments public select"
    ON storage.objects FOR SELECT
    USING (bucket_id = 'attachments');
EXCEPTION WHEN duplicate_object THEN
  NULL;
END $$;

DO $$
BEGIN
  CREATE POLICY "attachments authenticated insert"
    ON storage.objects FOR INSERT
    WITH CHECK (bucket_id = 'attachments');
EXCEPTION WHEN duplicate_object THEN
  NULL;
END $$;

DROP POLICY IF EXISTS circulars_update_active_admins
ON public.circulars;

CREATE POLICY circulars_update_active_admins
ON public.circulars
FOR UPDATE
TO authenticated
USING (
  neighborhood_id IN (
    SELECT admins.neighborhood_id
    FROM public.neighborhood_admins admins
    WHERE admins.admin_auth_id = auth.uid()
      AND admins.status = 'active'
  )
)
WITH CHECK (
  neighborhood_id IN (
    SELECT admins.neighborhood_id
    FROM public.neighborhood_admins admins
    WHERE admins.admin_auth_id = auth.uid()
      AND admins.status = 'active'
  )
);

DROP POLICY IF EXISTS circulars_delete_active_admins
ON public.circulars;

CREATE POLICY circulars_delete_active_admins
ON public.circulars
FOR DELETE
TO authenticated
USING (
  neighborhood_id IN (
    SELECT admins.neighborhood_id
    FROM public.neighborhood_admins admins
    WHERE admins.admin_auth_id = auth.uid()
      AND admins.status = 'active'
  )
);

DROP POLICY IF EXISTS event_applications_delete_active_admins
ON public.event_applications;

CREATE POLICY event_applications_delete_active_admins
ON public.event_applications
FOR DELETE
TO authenticated
USING (
  neighborhood_id IN (
    SELECT admins.neighborhood_id
    FROM public.neighborhood_admins admins
    WHERE admins.admin_auth_id = auth.uid()
      AND admins.status = 'active'
  )
);

NOTIFY pgrst, 'reload schema';

COMMENT ON COLUMN public.circulars.category IS '発信種別。circular=電子回覧板、notice/info=連絡、event=イベント、assembly=総会通知。';
COMMENT ON COLUMN public.circulars.is_pushed IS 'trueの場合、LINEへプッシュ通知メッセージを送信する対象。falseの場合、電子掲示板への掲示のみ。';
COMMENT ON COLUMN public.circulars.event_time IS 'イベント・総会の時間表示用テキスト。例: 午前10時から、受付9:30／開始10:00、書面開催。';
COMMENT ON COLUMN public.circulars.proxy_template_text IS '総会通知で会員に提示する委任状の定型本文。欠席返信時に会員が日付・名前とともに返信する。';
COMMENT ON COLUMN public.circulars.attachments IS '発信に添付した画像/PDFのURL、ファイル名、MIME種別を格納するJSON配列。';
COMMENT ON COLUMN public.event_applications.proxy_text IS '欠席返信時に会員が入力した委任状本文。';
COMMENT ON COLUMN public.event_applications.proxy_signed_date IS '委任状に記載する日付。';
COMMENT ON COLUMN public.event_applications.proxy_signer_name IS '委任状に記載する本人名。';
COMMENT ON COLUMN public.event_applications.proxy_agent_name IS '委任状に記載する代理人名。入力がない場合はPDFに代理人欄を表示しない。';
COMMENT ON TABLE public.event_applications IS 'イベント参加返信と総会出欠返信を保存する。総会欠席時はproxy_text/proxy_signed_date/proxy_signer_name/proxy_agent_nameに委任状内容を保存し、従来添付がある場合はproxy_file_urlにも保存する。';
