-- 総会会計年度の確定、改版スナップショット、代表者による訂正履歴。

CREATE TABLE IF NOT EXISTS public.assembly_year_closures (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  neighborhood_id BIGINT NOT NULL REFERENCES public.neighborhoods(id) ON DELETE RESTRICT,
  fiscal_year INTEGER NOT NULL CHECK (fiscal_year BETWEEN 2000 AND 2200),
  status TEXT NOT NULL DEFAULT 'locked' CHECK (status IN ('locked', 'unlocked')),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision > 0),
  locked_at TIMESTAMPTZ,
  locked_by UUID,
  unlocked_at TIMESTAMPTZ,
  unlocked_by UUID,
  unlock_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (neighborhood_id, fiscal_year)
);

CREATE TABLE IF NOT EXISTS public.assembly_year_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  closure_id BIGINT NOT NULL REFERENCES public.assembly_year_closures(id) ON DELETE RESTRICT,
  revision INTEGER NOT NULL CHECK (revision > 0),
  neighborhood_id BIGINT NOT NULL REFERENCES public.neighborhoods(id) ON DELETE RESTRICT,
  fiscal_year INTEGER NOT NULL CHECK (fiscal_year BETWEEN 2000 AND 2200),
  categories JSONB NOT NULL DEFAULT '[]'::JSONB,
  budgets JSONB NOT NULL DEFAULT '[]'::JSONB,
  settlements JSONB NOT NULL DEFAULT '[]'::JSONB,
  fee_rows JSONB NOT NULL DEFAULT '[]'::JSONB,
  fee_revenue NUMERIC NOT NULL DEFAULT 0,
  captured_by UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (closure_id, revision)
);

CREATE TABLE IF NOT EXISTS public.assembly_year_lock_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  closure_id BIGINT NOT NULL REFERENCES public.assembly_year_closures(id) ON DELETE RESTRICT,
  neighborhood_id BIGINT NOT NULL REFERENCES public.neighborhoods(id) ON DELETE RESTRICT,
  fiscal_year INTEGER NOT NULL,
  revision INTEGER NOT NULL,
  event_type TEXT NOT NULL CHECK (event_type IN ('locked', 'unlocked', 'relocked')),
  reason TEXT,
  actor_auth_id UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.assembly_record_correction_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  closure_id BIGINT NOT NULL REFERENCES public.assembly_year_closures(id) ON DELETE RESTRICT,
  neighborhood_id BIGINT NOT NULL REFERENCES public.neighborhoods(id) ON DELETE RESTRICT,
  fiscal_year INTEGER NOT NULL,
  table_name TEXT NOT NULL CHECK (table_name IN ('assembly_budgets', 'assembly_settlements')),
  record_id TEXT,
  operation TEXT NOT NULL CHECK (operation IN ('INSERT', 'UPDATE', 'DELETE')),
  before_data JSONB,
  after_data JSONB,
  actor_auth_id UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS assembly_year_snapshots_lookup
  ON public.assembly_year_snapshots (neighborhood_id, fiscal_year, revision DESC);
CREATE INDEX IF NOT EXISTS assembly_year_lock_events_lookup
  ON public.assembly_year_lock_events (neighborhood_id, fiscal_year, created_at DESC);
CREATE INDEX IF NOT EXISTS assembly_record_correction_lookup
  ON public.assembly_record_correction_audit (neighborhood_id, fiscal_year, created_at DESC);

CREATE OR REPLACE FUNCTION public.assembly_actor_is_admin(target_neighborhood_id BIGINT)
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.neighborhood_admins admins
    WHERE admins.neighborhood_id = target_neighborhood_id
      AND admins.status = 'active'
      AND (
        admins.admin_auth_id::TEXT = auth.uid()::TEXT
        OR lower(admins.admin_email) = lower(COALESCE(auth.jwt() ->> 'email', ''))
      )
  ) OR EXISTS (
    SELECT 1
    FROM public.neighborhoods town
    WHERE town.id = target_neighborhood_id
      AND town.admin_auth_id::TEXT = auth.uid()::TEXT
  );
$$;

CREATE OR REPLACE FUNCTION public.assembly_actor_is_representative(target_neighborhood_id BIGINT)
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.neighborhoods town
    WHERE town.id = target_neighborhood_id
      AND (
        town.admin_auth_id::TEXT = auth.uid()::TEXT
        OR lower(town.admin_email) = lower(COALESCE(auth.jwt() ->> 'email', ''))
      )
  );
$$;

CREATE OR REPLACE FUNCTION public.guard_finalized_assembly_record()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  old_closure public.assembly_year_closures;
  new_closure public.assembly_year_closures;
BEGIN
  IF TG_OP <> 'INSERT' THEN
    SELECT * INTO old_closure
    FROM public.assembly_year_closures
    WHERE neighborhood_id = OLD.neighborhood_id AND fiscal_year = OLD.fiscal_year;
  END IF;

  IF TG_OP <> 'DELETE' THEN
    SELECT * INTO new_closure
    FROM public.assembly_year_closures
    WHERE neighborhood_id = NEW.neighborhood_id AND fiscal_year = NEW.fiscal_year;
  END IF;

  IF old_closure.status = 'locked' OR new_closure.status = 'locked' THEN
    RAISE EXCEPTION '確定済み年度の総会会計データは変更できません。代表者が確定を解除してください。';
  END IF;

  IF (
    (old_closure.status = 'unlocked' AND NOT public.assembly_actor_is_representative(old_closure.neighborhood_id))
    OR (new_closure.status = 'unlocked' AND NOT public.assembly_actor_is_representative(new_closure.neighborhood_id))
  ) THEN
    RAISE EXCEPTION '確定解除後の総会会計訂正は代表者だけが実行できます。';
  END IF;

  RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$;

DROP TRIGGER IF EXISTS assembly_budgets_guard_finalized ON public.assembly_budgets;
CREATE TRIGGER assembly_budgets_guard_finalized
BEFORE INSERT OR UPDATE OR DELETE ON public.assembly_budgets
FOR EACH ROW EXECUTE FUNCTION public.guard_finalized_assembly_record();

DROP TRIGGER IF EXISTS assembly_settlements_guard_finalized ON public.assembly_settlements;
CREATE TRIGGER assembly_settlements_guard_finalized
BEFORE INSERT OR UPDATE OR DELETE ON public.assembly_settlements
FOR EACH ROW EXECUTE FUNCTION public.guard_finalized_assembly_record();

CREATE OR REPLACE FUNCTION public.audit_unlocked_assembly_correction()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  target_neighborhood_id BIGINT := COALESCE(NEW.neighborhood_id, OLD.neighborhood_id);
  target_fiscal_year INTEGER := COALESCE(NEW.fiscal_year, OLD.fiscal_year);
  target_record_id TEXT := COALESCE(NEW.id, OLD.id)::TEXT;
  closure public.assembly_year_closures;
BEGIN
  SELECT * INTO closure
  FROM public.assembly_year_closures
  WHERE neighborhood_id = target_neighborhood_id AND fiscal_year = target_fiscal_year;

  IF closure.id IS NOT NULL AND closure.status = 'unlocked' THEN
    INSERT INTO public.assembly_record_correction_audit (
      closure_id, neighborhood_id, fiscal_year, table_name, record_id,
      operation, before_data, after_data, actor_auth_id
    ) VALUES (
      closure.id, target_neighborhood_id, target_fiscal_year, TG_TABLE_NAME, target_record_id,
      TG_OP,
      CASE WHEN TG_OP = 'INSERT' THEN NULL ELSE to_jsonb(OLD) END,
      CASE WHEN TG_OP = 'DELETE' THEN NULL ELSE to_jsonb(NEW) END,
      auth.uid()
    );
  END IF;

  RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$;

DROP TRIGGER IF EXISTS assembly_budgets_audit_unlocked ON public.assembly_budgets;
CREATE TRIGGER assembly_budgets_audit_unlocked
AFTER INSERT OR UPDATE OR DELETE ON public.assembly_budgets
FOR EACH ROW EXECUTE FUNCTION public.audit_unlocked_assembly_correction();

DROP TRIGGER IF EXISTS assembly_settlements_audit_unlocked ON public.assembly_settlements;
CREATE TRIGGER assembly_settlements_audit_unlocked
AFTER INSERT OR UPDATE OR DELETE ON public.assembly_settlements
FOR EACH ROW EXECUTE FUNCTION public.audit_unlocked_assembly_correction();

CREATE OR REPLACE FUNCTION public.finalize_assembly_year(p_neighborhood_id BIGINT, p_fiscal_year INTEGER)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  closure public.assembly_year_closures;
  next_revision INTEGER;
  event_name TEXT;
  category_rows JSONB;
  budget_rows JSONB;
  settlement_rows JSONB;
  fee_rows_json JSONB;
  fee_total NUMERIC;
BEGIN
  PERFORM pg_advisory_xact_lock(hashtextextended('assembly-year:' || p_neighborhood_id || ':' || p_fiscal_year, 0));
  IF p_fiscal_year NOT BETWEEN 2000 AND 2200 THEN RAISE EXCEPTION '会計年度が不正です。'; END IF;
  IF NOT public.assembly_actor_is_admin(p_neighborhood_id) THEN RAISE EXCEPTION '総会会計年度を確定する権限がありません。'; END IF;

  SELECT * INTO closure
  FROM public.assembly_year_closures
  WHERE neighborhood_id = p_neighborhood_id AND fiscal_year = p_fiscal_year
  FOR UPDATE;

  IF closure.id IS NOT NULL AND closure.status = 'locked' THEN RAISE EXCEPTION '%年度は確定済みです。', p_fiscal_year; END IF;
  IF closure.id IS NOT NULL AND NOT public.assembly_actor_is_representative(p_neighborhood_id) THEN
    RAISE EXCEPTION '確定解除後の再確定は代表者だけが実行できます。';
  END IF;

  PERFORM 1 FROM public.assembly_budgets
  WHERE neighborhood_id = p_neighborhood_id AND fiscal_year = p_fiscal_year FOR UPDATE;
  PERFORM 1 FROM public.assembly_settlements
  WHERE neighborhood_id = p_neighborhood_id AND fiscal_year = p_fiscal_year FOR UPDATE;

  SELECT COALESCE(jsonb_agg(to_jsonb(category) ORDER BY category.sort_order, category.id), '[]'::JSONB)
  INTO category_rows
  FROM public.assembly_categories category
  WHERE category.neighborhood_id = p_neighborhood_id AND COALESCE(category.is_active, TRUE) = TRUE;

  SELECT COALESCE(jsonb_agg(to_jsonb(budget) ORDER BY budget.category_id, budget.id), '[]'::JSONB)
  INTO budget_rows
  FROM public.assembly_budgets budget
  WHERE budget.neighborhood_id = p_neighborhood_id AND budget.fiscal_year = p_fiscal_year;

  SELECT COALESCE(jsonb_agg(to_jsonb(settlement) ORDER BY settlement.paid_date DESC, settlement.id DESC), '[]'::JSONB)
  INTO settlement_rows
  FROM public.assembly_settlements settlement
  WHERE settlement.neighborhood_id = p_neighborhood_id AND settlement.fiscal_year = p_fiscal_year;

  SELECT
    COALESCE(jsonb_agg(to_jsonb(fee) ORDER BY fee.id), '[]'::JSONB),
    COALESCE(SUM(COALESCE(fee.paid_amount, COALESCE(fee.paid_amount_cash, 0) + COALESCE(fee.paid_amount_stripe, 0), 0)), 0)
  INTO fee_rows_json, fee_total
  FROM public.fee_records fee
  WHERE fee.neighborhood_id = p_neighborhood_id
    AND COALESCE(fee.fiscal_year, fee.year) = p_fiscal_year;

  next_revision := COALESCE(closure.revision, 0) + 1;
  event_name := CASE WHEN closure.id IS NULL THEN 'locked' ELSE 'relocked' END;

  INSERT INTO public.assembly_year_closures (
    neighborhood_id, fiscal_year, status, revision, locked_at, locked_by,
    unlocked_at, unlocked_by, unlock_reason, updated_at
  ) VALUES (
    p_neighborhood_id, p_fiscal_year, 'locked', next_revision, NOW(), auth.uid(),
    NULL, NULL, NULL, NOW()
  )
  ON CONFLICT (neighborhood_id, fiscal_year) DO UPDATE SET
    status = 'locked', revision = EXCLUDED.revision, locked_at = NOW(), locked_by = auth.uid(),
    unlocked_at = NULL, unlocked_by = NULL, unlock_reason = NULL, updated_at = NOW()
  RETURNING * INTO closure;

  INSERT INTO public.assembly_year_snapshots (
    closure_id, revision, neighborhood_id, fiscal_year,
    categories, budgets, settlements, fee_rows, fee_revenue, captured_by
  ) VALUES (
    closure.id, next_revision, p_neighborhood_id, p_fiscal_year,
    category_rows, budget_rows, settlement_rows, fee_rows_json, fee_total, auth.uid()
  );

  INSERT INTO public.assembly_year_lock_events (
    closure_id, neighborhood_id, fiscal_year, revision, event_type, actor_auth_id
  ) VALUES (closure.id, p_neighborhood_id, p_fiscal_year, next_revision, event_name, auth.uid());

  RETURN jsonb_build_object(
    'status', 'locked', 'revision', next_revision,
    'categoryCount', jsonb_array_length(category_rows),
    'budgetCount', jsonb_array_length(budget_rows),
    'settlementCount', jsonb_array_length(settlement_rows),
    'feeRevenue', fee_total
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.unlock_assembly_year(p_neighborhood_id BIGINT, p_fiscal_year INTEGER, p_reason TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  closure public.assembly_year_closures;
BEGIN
  PERFORM pg_advisory_xact_lock(hashtextextended('assembly-year:' || p_neighborhood_id || ':' || p_fiscal_year, 0));
  IF NOT public.assembly_actor_is_representative(p_neighborhood_id) THEN RAISE EXCEPTION '総会会計の確定を解除できるのは代表者だけです。'; END IF;
  IF length(btrim(COALESCE(p_reason, ''))) < 3 THEN RAISE EXCEPTION '確定を解除する理由を3文字以上で入力してください。'; END IF;

  SELECT * INTO closure
  FROM public.assembly_year_closures
  WHERE neighborhood_id = p_neighborhood_id AND fiscal_year = p_fiscal_year
  FOR UPDATE;

  IF closure.id IS NULL OR closure.status <> 'locked' THEN RAISE EXCEPTION '%年度は確定されていません。', p_fiscal_year; END IF;

  UPDATE public.assembly_year_closures SET
    status = 'unlocked', unlocked_at = NOW(), unlocked_by = auth.uid(),
    unlock_reason = btrim(p_reason), updated_at = NOW()
  WHERE id = closure.id;

  INSERT INTO public.assembly_year_lock_events (
    closure_id, neighborhood_id, fiscal_year, revision, event_type, reason, actor_auth_id
  ) VALUES (
    closure.id, p_neighborhood_id, p_fiscal_year, closure.revision, 'unlocked', btrim(p_reason), auth.uid()
  );

  RETURN jsonb_build_object('status', 'unlocked', 'revision', closure.revision);
END;
$$;

ALTER TABLE public.assembly_year_closures ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assembly_year_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assembly_year_lock_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assembly_record_correction_audit ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS assembly_year_closures_admin_read ON public.assembly_year_closures;
CREATE POLICY assembly_year_closures_admin_read ON public.assembly_year_closures FOR SELECT TO authenticated
USING (public.assembly_actor_is_admin(neighborhood_id));

DROP POLICY IF EXISTS assembly_year_snapshots_admin_read ON public.assembly_year_snapshots;
CREATE POLICY assembly_year_snapshots_admin_read ON public.assembly_year_snapshots FOR SELECT TO authenticated
USING (public.assembly_actor_is_admin(neighborhood_id));

DROP POLICY IF EXISTS assembly_year_lock_events_admin_read ON public.assembly_year_lock_events;
CREATE POLICY assembly_year_lock_events_admin_read ON public.assembly_year_lock_events FOR SELECT TO authenticated
USING (public.assembly_actor_is_admin(neighborhood_id));

DROP POLICY IF EXISTS assembly_record_correction_admin_read ON public.assembly_record_correction_audit;
CREATE POLICY assembly_record_correction_admin_read ON public.assembly_record_correction_audit FOR SELECT TO authenticated
USING (public.assembly_actor_is_admin(neighborhood_id));

GRANT SELECT ON public.assembly_year_closures, public.assembly_year_snapshots, public.assembly_year_lock_events, public.assembly_record_correction_audit TO authenticated;
GRANT EXECUTE ON FUNCTION public.finalize_assembly_year(BIGINT, INTEGER) TO authenticated;
GRANT EXECUTE ON FUNCTION public.unlock_assembly_year(BIGINT, INTEGER, TEXT) TO authenticated;

COMMENT ON TABLE public.assembly_year_closures IS '町内会・自治会ごとの総会会計年度確定状態。';
COMMENT ON TABLE public.assembly_year_snapshots IS '総会会計年度確定時点の科目・予算・決算明細・会費連携データの改版スナップショット。';
COMMENT ON TABLE public.assembly_year_lock_events IS '総会会計年度の確定・解除・再確定履歴。';
COMMENT ON TABLE public.assembly_record_correction_audit IS '代表者が確定解除後に行った総会会計データの訂正履歴。';

NOTIFY pgrst, 'reload schema';
